// <auto-generated />
using System;
using MVC_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_Project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250322125300_SeedingDataForTables")]
    partial class SeedingDataForTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC_Project.Models.ProgressTracking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Goals")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoodRating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgressNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("ProgressTrackings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Goals = "Reduce anxiety by 20%",
                            MoodRating = "Good",
                            ProgressNotes = "Feeling better after the session.",
                            UserID = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Goals = "Manage stress levels",
                            MoodRating = "AboveAverage",
                            ProgressNotes = "Noted improvement in mood.",
                            UserID = 2
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2025, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Goals = "Improve communication skills",
                            MoodRating = "VeryGood",
                            ProgressNotes = "Made progress in expressing feelings.",
                            UserID = 3
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Goals = "Continue anxiety management",
                            MoodRating = "Excellent",
                            ProgressNotes = "Feeling more confident.",
                            UserID = 1
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2025, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Goals = "Work on OCD management",
                            MoodRating = "Good",
                            ProgressNotes = "Making steady progress.",
                            UserID = 2
                        });
                });

            modelBuilder.Entity("MVC_Project.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TherapistID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TherapistID");

                    b.HasIndex("UserID");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Rating = "Excellent",
                            ReviewDate = new DateTime(2025, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewText = "Dr. Hazem Mofdi was very understanding and helpful. Highly recommend!",
                            TherapistID = 1,
                            UserID = 1
                        },
                        new
                        {
                            Id = 2,
                            Rating = "Good",
                            ReviewDate = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewText = "Dr. Hassan Atef provided useful stress management tips. Very professional.",
                            TherapistID = 2,
                            UserID = 2
                        },
                        new
                        {
                            Id = 3,
                            Rating = "Excellent",
                            ReviewDate = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewText = "Dr. Rahma Tarek helped me a lot with my trauma recovery. Thank you!",
                            TherapistID = 3,
                            UserID = 3
                        },
                        new
                        {
                            Id = 4,
                            Rating = "Good",
                            ReviewDate = new DateTime(2025, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewText = "Dr. Nancy Saad is very knowledgeable about workplace stress. Great session!",
                            TherapistID = 4,
                            UserID = 1
                        },
                        new
                        {
                            Id = 5,
                            Rating = "Excellent",
                            ReviewDate = new DateTime(2025, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewText = "Dr. Hamss Mohammed is amazing at OCD management. Highly recommend!",
                            TherapistID = 5,
                            UserID = 2
                        });
                });

            modelBuilder.Entity("MVC_Project.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("SessionTime")
                        .HasColumnType("time");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TherapistID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TherapistID");

                    b.HasIndex("UserID");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SessionDate = new DateTime(2025, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SessionNotes = "Initial consultation for anxiety management.",
                            SessionStatus = "Booked",
                            SessionTime = new TimeSpan(0, 10, 0, 0, 0),
                            SessionType = "VideoCall",
                            TherapistID = 1,
                            UserID = 1
                        },
                        new
                        {
                            Id = 2,
                            SessionDate = new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SessionNotes = "Follow-up session for stress management.",
                            SessionStatus = "Completed",
                            SessionTime = new TimeSpan(0, 14, 0, 0, 0),
                            SessionType = "Chat",
                            TherapistID = 2,
                            UserID = 2
                        },
                        new
                        {
                            Id = 3,
                            SessionDate = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SessionNotes = "Discussion on trauma recovery.",
                            SessionStatus = "Booked",
                            SessionTime = new TimeSpan(0, 16, 0, 0, 0),
                            SessionType = "Chat",
                            TherapistID = 3,
                            UserID = 3
                        },
                        new
                        {
                            Id = 4,
                            SessionDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SessionNotes = "Session on workplace stress and burnout.",
                            SessionStatus = "Booked",
                            SessionTime = new TimeSpan(0, 11, 0, 0, 0),
                            SessionType = "VideoCall",
                            TherapistID = 4,
                            UserID = 1
                        },
                        new
                        {
                            Id = 5,
                            SessionDate = new DateTime(2025, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SessionNotes = "Session on OCD management.",
                            SessionStatus = "Booked",
                            SessionTime = new TimeSpan(0, 13, 0, 0, 0),
                            SessionType = "Chat",
                            TherapistID = 5,
                            UserID = 2
                        });
                });

            modelBuilder.Entity("MVC_Project.Models.Therapist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Availability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Therapists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Availability = "Mon-Fri, 9 AM - 5 PM",
                            Bio = "Experienced therapist with 10+ years of practice. Specializes in anxiety and depression.",
                            Email = "HazemMofdi11@gmail.com",
                            FName = "Hazem",
                            LName = "Mofdi",
                            Rating = 5
                        },
                        new
                        {
                            Id = 2,
                            Availability = "Tue-Thu, 10 AM - 6 PM",
                            Bio = "Specializes in stress management and burnout. Helps clients develop coping strategies.",
                            Email = "HassanAtef10@gmail.com",
                            FName = "Hassan",
                            LName = "Atef",
                            Rating = 5
                        },
                        new
                        {
                            Id = 3,
                            Availability = "Mon-Wed, 11 AM - 7 PM",
                            Bio = "Specializes in trauma-informed therapist who specializes in helping clients heal from PTSD and complex trauma",
                            Email = "RahmaTarek111@gmail.com",
                            FName = "Rahma",
                            LName = "Tarek",
                            Rating = 5
                        },
                        new
                        {
                            Id = 4,
                            Availability = "Wed-Fri, 12 PM - 8 PM",
                            Bio = "Specializes in workplace stress and burnout. She helps clients manage stress, improve work-life balance, and develop resilience through mindfulness and stress-reduction techniques.",
                            Email = "NancySaad111@gmail.com",
                            FName = "Nancy",
                            LName = "Saad",
                            Rating = 5
                        },
                        new
                        {
                            Id = 5,
                            Availability = "Mon-Thu, 9 AM - 4 PM",
                            Bio = "licensed psychologist specializing in the treatment of Obsessive-Compulsive Disorder (OCD), She helps clients reduce compulsions and manage intrusive thoughts. With over 10 years of experience",
                            Email = "HamssMohamed111@gmail.com",
                            FName = "Hamss",
                            LName = "Mohammed",
                            Rating = 5
                        });
                });

            modelBuilder.Entity("MVC_Project.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HealthAssessmentResults")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Preferences")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1999, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "SarahAhmed12@gmail.com",
                            FName = "Sarah",
                            Gender = "Female",
                            HealthAssessmentResults = "Anxiety",
                            LName = "Ahmed",
                            Password = "123456",
                            PhoneNumber = "01012345678",
                            Preferences = "Prefers video calls"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2003, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "MohammedMahmoud33@gmail.com",
                            FName = "Mohammed",
                            Gender = "Male",
                            HealthAssessmentResults = "OCD",
                            LName = "Mahmoud",
                            Password = "1234567",
                            PhoneNumber = "01033345678",
                            Preferences = "Prefers video calls"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2000, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ToqaAli25@gmail.com",
                            FName = "Toqa",
                            Gender = "Male",
                            HealthAssessmentResults = "MildDepression",
                            LName = "Ali",
                            Password = "12345678",
                            PhoneNumber = "01044445678",
                            Preferences = "Prefers Chat"
                        });
                });

            modelBuilder.Entity("MVC_Project.Models.ProgressTracking", b =>
                {
                    b.HasOne("MVC_Project.Models.User", "User")
                        .WithMany("ProgressTrackings")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MVC_Project.Models.Review", b =>
                {
                    b.HasOne("MVC_Project.Models.Therapist", "Therapist")
                        .WithMany("Review")
                        .HasForeignKey("TherapistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVC_Project.Models.User", "User")
                        .WithMany("Review")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Therapist");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MVC_Project.Models.Session", b =>
                {
                    b.HasOne("MVC_Project.Models.Therapist", "Therapist")
                        .WithMany("Sessions")
                        .HasForeignKey("TherapistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVC_Project.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Therapist");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MVC_Project.Models.Therapist", b =>
                {
                    b.Navigation("Review");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("MVC_Project.Models.User", b =>
                {
                    b.Navigation("ProgressTrackings");

                    b.Navigation("Review");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
